name: Build and Deploy Windows

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Qt and dependencies
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
          arch: win64_mingw

      - name: Build
        run: |
          cmake -B build -G "MinGW Makefiles"
          cmake --build build

      - name: Deploy Qt dependencies (windeployqt)
        run: |
          $env:Path += ";$Env:Qt6_DIR/bin"
          & "$Env:Qt6_DIR/bin/windeployqt.exe" bin\MyQtApp.exe
          & "$Env:Qt6_DIR/bin/windeployqt.exe" bin\ChatServer.exe

      - name: Zip deployment folder
        run: |
          Compress-Archive -Path bin\* -DestinationPath chat-windows-deploy.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-deploy
          path: chat-windows-deploy.zip