name: Build Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qtbase5-dev-tools qt6-base-dev cmake g++

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: build/*